chain:
  chain_id: "one"
  base_url: "localhost:9090"
  keyring_type: "memory"
  gas_limit: 200000

db:
  host: localhost
  port: 5433
  user: postgres
  password: postgres
  db-name: skeleton_service
  config-directory: "dbschema/migrations"
  auto-migrate: true

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

http:
  port: 3000

rabbit:
  url: "amqp://guest:guest@localhost:5672/"

extra:
  mnemonic: "panda property decide blush omit cross oak deposit banana wise warrior burden depth oil beach stumble swim tattoo ancient next grab merge manual remain"